language: node_js
sudo: false

node_js:
  - '7'

before_script:
  - export PATH=$(pwd)/node_modules/.bin:$PATH

install:
  - npm install
  - npm install bower -g
  - bower install

script:
  - npm run package-linux
  - npm run package-osx
  - zip -qr CAMV-darwin-x64.zip CAMV-darwin-x64
  - zip -qr CAMV-linux-ia32.zip CAMV-linux-ia32
  - zip -qr CAMV-linux-x64.zip  CAMV-linux-x64

deploy:
  provider: releases
  file:
    - "CAMV-darwin-x64.zip"
    - "CAMV-linux-ia32.zip"
    - "CAMV-linux-x64.zip"
  skip_cleanup: true
  on:
    repo: naderm/CAMV
    tags: true
