language: node_js
sudo: false

node_js:
  - '7'

before_script:
  - export PATH=$(pwd)/node_modules/.bin:$PATH

install:
  - npm install
  - npm install bower -g
  - bower install

script:
  - npm run package-linux
  - npm run package-osx
  - zip -qr out/CAMV-darwin-x64.zip out/CAMV-darwin-x64
  - zip -qr out/CAMV-linux-ia32.zip out/CAMV-linux-ia32
  - zip -qr out/CAMV-linux-x64.zip  out/CAMV-linux-x64

# deploy:
#   provider: releases
#   file:
#     - "out/CAMV-darwin-x64.zip"
#     - "out/CAMV-linux-ia32.zip"
#     - "out/CAMV-linux-x64.zip"
#   skip_cleanup: true
#   on:
#     repo: white-lab/CAMV
#     tags: true
