version: Build {build}

skip_non_tags: true

# build:
#     verbosity: minimal

environment:
    matrix:
        - nodejs_version: "7"

install:
    - ps: Install-Product node $env:nodejs_version
    - "npm install"
    - "npm install bower -g"
    - "bower install"

# test_script:
#     - npm test

build_script:
    - npm run package

artifacts:
    - path: "CAMV-darwin-x64"
    - path: "CAMV-linux-ia32"
    - path: "CAMV-linux-x64"
    - path: "CAMV-mas-x64"
    - path: "CAMV-win32-ia32"
    - path: "CAMV-win32-x64"

deploy:
    - provider: GitHub
      auth_token:
        secure: Vt90BNYB5BI/GtFTilnFdNNEC8T+/szE6cmO3M3gpMaMRXzE4p+XNdAHyymTxnJN
      description: "Computer Assisted Manual Validation for Mass Spectrometry Proteomics"
      artifact: /CAMV-.*\.zip/
      draft: false
      prerelease: false
      on:
        branch: master
        appveyor_repo_tag: true
