version: Build {build}

skip_non_tags: true

environment:
    matrix:
        - nodejs_version: "7"
          platform: x64

install:
    - ps: Install-Product node $env:nodejs_version
    - "npm install"
    - "npm install bower -g"
    - "bower install"

# test_script:
#     - npm test

build_script:
    - npm run make

artifacts:
    - path: "out/make/CAMV-win32-x64.zip"

deploy:
    - provider: GitHub
      auth_token:
        secure: Vt90BNYB5BI/GtFTilnFdNNEC8T+/szE6cmO3M3gpMaMRXzE4p+XNdAHyymTxnJN
      description: "Computer Assisted Manual Validation for Mass Spectrometry Proteomics"
      artifact: /CAMV-.*\.zip/
      draft: false
      prerelease: false
      on:
        branch: master
        appveyor_repo_tag: true
